# Generated by Django 5.0.4 on 2024-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_product_from_age_alter_product_under_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
    ]
